queue doc changes to copilot agent until after-change-functions
copilot-emacs/copilot.el pull request #176
Opened 2023-09-01 01:35 UTC by raymond-w-ko

I am not an Emacs expert, but my hypothesis is that jsonrpc-notify causes buffer navigation to occur, which causes the (org-todo) function to break when called twice in a row.

This fixes issue:
https://github.com/zerolfx/copilot.el/issues/172

2023-09-14 15:04 UTC, raymond-w-ko commented
The original pull request would never have worked properly, since I thought `nreverse` reversed in place, but it was actually dropping the subsequent set of changes, meaning the buffer would have been desynced.

There is also some other extra stuff here, like the `(copilot-resync-buffer)` command, and a rewrite to fix `save-*` nesting order.

But assuming this is the wrong way to fix #172, there isn't anything too important here to merge.

2023-12-12 10:58 UTC, emil-vdw commented
> But assuming this is the wrong way to fix #172, there isn't anything too important here to merge.

@raymond-w-ko I am confused. does this PR fix the linked issue or not?

2023-12-12 13:12 UTC, emil-vdw requested changes

2023-12-12 13:12 UTC, emil-vdw commented on copilot.el
> +                     ;; (with-output-to-string (prin1 content-changes)))
```suggestion
```

2023-12-12 13:12 UTC, emil-vdw commented on copilot.el
> +a list that needs to be reversed")
```suggestion
a list that needs to be reversed")

```

2023-12-12 13:12 UTC, emil-vdw commented on copilot.el
> +    (copilot--notify 'textDocument/didChange x))
```suggestion
  (dolist (content-change (nreverse copilot--doc-change-queue))
    (copilot--notify 'textDocument/didChange content-change))
```

2023-12-12 13:12 UTC, emil-vdw commented on copilot.el
> +  (copilot--flush-pending-doc-changes)
Why is this called in all of these functions? :thinking:

2023-12-12 13:12 UTC, emil-vdw commented on copilot.el
> +          (let* ((p (point))
```suggestion
```

2023-12-12 13:12 UTC, emil-vdw commented on copilot.el
> +  "Resyncs the buffer state in the copilot agent by sending the entire buffer to the agent."
It might be good to document the fact that the entire buffer might not be synced when `(point-max)` > `copilot-max-char`.

2024-02-13 09:53 UTC, emil-vdw commented
I will push changes and get this merged.

2024-03-10 09:41 UTC, jcs090218 commented on copilot.el
> +      (when copilot--change-idle-timer (cancel-timer copilot--change-idle-timer))
You might to use the function `timerp` here.

2024-03-10 09:41 UTC, jcs090218 commented on copilot.el
> +                           (setq copilot--change-idle-timer nil)))))))))))
Why are we setting the timer to `nil` here? 🤔 I prefer not to nullify the timer, even if that's the end of execution.

2024-03-10 09:41 UTC, jcs090218 commented on copilot.el
> +  (setq copilot--doc-change-queue '()))
It's better just to set it to `nil`.

2024-03-10 09:41 UTC, jcs090218 commented on copilot.el
> +  :type 'number)
Missing the property `:group`.

2024-03-10 10:09 UTC, emil-vdw commented on copilot.el
> +  (setq copilot--doc-change-queue '()))
Then the `dolist` call will error. Could wrap it in a check though.

2024-03-10 10:10 UTC, emil-vdw commented on copilot.el
> +                           (setq copilot--change-idle-timer nil)))))))))))
Honestly, I took this code straight from the `eglot` implementation. Probably good to clean up and have a easy way to know if the timer has finished execution?

2024-03-10 10:17 UTC, emil-vdw commented on copilot.el
> +  (setq copilot--doc-change-queue '()))
Will also make the logic to `push` more cumbersome no?

2024-03-10 10:39 UTC, jcs090218 commented on copilot.el
> +  (setq copilot--doc-change-queue '()))
What error is it? It shouldn't give you any error. 🤔 All these safely executed:

```elisp
(dolist (_ (nreverse nil)))
(nreverse nil)
(dolist (_ nil))
```

2024-03-10 10:42 UTC, emil-vdw commented on copilot.el
> +  (setq copilot--doc-change-queue '()))
Fair enough! :smile:

2024-03-10 10:47 UTC, jcs090218 commented on copilot.el
> +                           (setq copilot--change-idle-timer nil)))))))))))
See the function description from `cancel-timer`:

```
Remove TIMER from the list of active timers.
```

Setting the variable to `nil` does not seem to remove the timer. I assumed the timer list would grow indefinitely.

2024-03-10 11:17 UTC, emil-vdw commented on copilot.el
> +                           (setq copilot--change-idle-timer nil)))))))))))
The timer doesn't need to be cancelled because it has already executed and it is non-repeating (the var containing timer is set to nil in the timer function body).

2024-03-11 00:35 UTC, jcs090218 approved these changes
LGTM. :)

Some nits that are good to resolve:

```
In toplevel form:
copilot.el:39:35: Warning: Alias for ‘copilot-completion-idle-delay’ should be declared before its referent

In copilot-diagnose:
copilot.el:311:7: Warning: reference to free variable ‘copilot-mode’

In copilot--handle-notification:
copilot.el:542:14: Warning: ‘mark-whole-buffer’ is for interactive use only.

In copilot--on-doc-change:
copilot.el:665:32: Warning: reference to free variable ‘copilot-mode’

In copilot--on-doc-focus:
copilot.el:675:14: Warning: reference to free variable ‘copilot-mode’

In copilot-async-start-process:
copilot.el:[105](https://github.com/copilot-emacs/copilot.el/actions/runs/8222298553/job/22483626619?pr=176#step:5:106)0:10: Warning: Unused lexical variable ‘name’

In end of data:
copilot.el:804:14: Warning: the function ‘vterm-insert’ is not known to be defined.
copilot.el:803:14: Warning: the function ‘vterm-delete-region’ is not known to be defined.
copilot.el:543:14: Warning: the function ‘org-sort-entries’ is not known to be defined.
copilot.el:532:54: Warning: the function ‘org-entry-get’ is not known to be defined.
copilot.el:532:26: Warning: the function ‘org-map-entries’ is not known to be defined.
```

But we can fix these warnings later.

2024-03-11 00:35 UTC, jcs090218 commented on copilot.el
> +                           (setq copilot--change-idle-timer nil)))))))))))
You are right. The timer will be removed by itself. 🤔 Thanks for the confirmation!

2024-03-13 09:18 UTC, emil-vdw commented
One last thing to check is that `copilot-panel-complete` also flushes pending messages before requesting completions.

2024-03-14 06:03 UTC, timcharper commented on copilot.el
> +(defcustom copilot-completion-idle-delay 0
what's the motivation for this change?

2024-03-14 06:08 UTC, timcharper commented on copilot.el
> +(cl-defmacro copilot--widening (&rest body)
It feels like this change doens't quite fit the PR description? Separate PR? Not clear to me why it's necessary since the point should be within the narrowed region, right?

2024-03-14 06:42 UTC, timcharper requested changes
Change appears to not create any regressions, however, I'm unable to reproduce the original issue on master, which causes me to wonder if we really understand what is broken?

[![asciicast](https://asciinema.org/a/rehfVyeT0q7An9g6voAUkperv.svg)](https://asciinema.org/a/rehfVyeT0q7An9g6voAUkperv)

I have concerns about the widen change. Why is this introduced with this PR? There's no explanation as to what motivated it, and it appears unrelated and also I cannot understand why it is needed (copilot operates right after the point, and the point should always be in a narrowed region? In my experiments, I have no trouble using copilot within a narrowed region. A separate issue should be filed.

[![asciicast](https://asciinema.org/a/pVuFhZuBsxtIromX1xvl49fTo.svg)](https://asciinema.org/a/pVuFhZuBsxtIromX1xvl49fTo)

In my recordings, I'm using Emacs 29.2, with the built-in version of org-mode, and a minimal environment (package-initialize, keycast-mode enabled, copilot-mode enabled (from source at commit 0d48e75dabef86b962b7a8bfcc7d3614a1201821)

Given that I can't reproduce the original issue on master, I'm wondering if this change is needed

2024-03-16 12:23 UTC, emil-vdw commented
@timcharper Although I did manage to reproduce the problem initially I am also not seeing it anymore on Emacs `29.2` org mode version `9.6.15`.

I do, however, feel like this is a good improvement nonetheless. That being deferring jsonrpc communication with the server to some idle time or until the user requests a completion (as implemented in and shamelessly stolen from `eglot`). This can still be "turned off" by setting the idle time low enough.

In any event, the PR title and description needs some work. I will update.

2025-03-30 15:18 UTC, bbatsov commented
I guess this should account for the changes in #363.

2025-04-17 07:42 UTC, bbatsov commented
@raymond-w-ko @emil-vdw Is this something you plan to continue working on or should we close it?

2025-04-22 11:04 UTC, emil-vdw commented
@bbatsov this needs a bit of work still and I'm not sure when I'll get back around to it. I've also been considering re-implementing this with the newer and simpler `track-changes` API.

I think you can close this for the time being. I will create a new PR in future :+1:.

2025-04-22 11:04 UTC, closed without merging