feat: Install server
copilot-emacs/copilot.el pull request #247
Opened 2024-01-29 08:58 UTC by jcs090218

For #120.

2024-01-29 09:00 UTC, jcs090218 commented on copilot.el
> +                                 (current-buffer))))))
From L193 are all indentation errors. 🤔

2024-01-29 09:00 UTC, jcs090218 commented on copilot.el
> +  :group 'copilot)
I've made this variable customizable so the user can choose what version to install.

2024-01-31 09:15 UTC, emil-vdw commented
As part of this PR, we would also get rid of the `dist` folder and current `chore` workflow no?

2024-01-31 09:21 UTC, zerolfx commented
@emil-vdw 
We may need two steps:
1. Prioritize using the agent.js installed by the new method then the old dist folder. If a user is using the agent.js from the dist folder, send a deprecation warning and ask them to install it via the new method.
2. Remove the dist folder and the chore workflow.

2024-01-31 09:31 UTC, zerolfx commented
@jcs090218 
Could you also modify `copilot--start-agent` to load the `agent.js` from the new installing method? 
It would be better if you check the currently installed version of the NPM package and send a warning if it is mismatched with `copilot-version`.

2024-01-31 09:51 UTC, zerolfx commented
> Prioritize using the agent.js installed by the new method then the old dist folder. If a user is using the agent.js from the dist folder, send a deprecation warning and ask them to install it via the new method.

@emil-vdw After giving it another thought, I realized that this step can be skipped. It's okay to delete `dist` after providing a new way to install them.

2024-01-31 10:07 UTC, jcs090218 commented
> We may need two steps:
> 
> 1. Prioritize using the agent.js installed by the new method then the old dist folder. If a user is using the agent.js from the dist folder, send a deprecation warning and ask them to install it via the new method.
> 2. Remove the dist folder and the chore workflow.

What if we prompt the user to install the server when it's not yet installed in the new location? This is much more straightforward IMO. 🤔 Then we can remove `dist` and `chore` workflow in this PR (or later).

> Could you also modify copilot--start-agent to load the agent.js from the new installing method? 
> It would be better if you check the currently installed version of the NPM package and send a warning if it is mismatched with copilot-version.

👍 Done.

2024-01-31 10:12 UTC, zerolfx commented
@jcs090218 Very cool! You solved the long-term issue!

One last request: 
Could you test the new installation method on Windows? (In case you have a Windows machine available.)

2024-01-31 10:15 UTC, jcs090218 commented
> Could you test the new installation method on Windows? (In case you have a Windows machine available.)

Actually, I need someone to test on Unix-line system (linux or macOS), because I'm using Windows now. 😂

2024-02-04 14:00 UTC, emil-vdw requested changes
I have a few concerns:
1. The reliability of the `copilot-node-server` npm package. Can we trust it to be available, up-to-date and not to be hijacked? Should we investigate whether to pull the agent distributables straight from the corresponding github tag of the official `copilot.vim` repo?
2. The fact that at some point a mismatch between the minimum required server version and `copilot.el` version will break the plugin (see comment below).

2024-02-04 14:00 UTC, emil-vdw commented on copilot.el
> +      (message "[WARN] Newer versions of the Copilot server are available for installation.
Why not warn here?
```suggestion
      (warn "Newer versions of the Copilot server are available for installation.
```

Also there are potentially some bigger issues with this approach. At some point we are going to add backwards incompatible changes (say chat functionality) that will just break if an older version of the server is installed?
For this same reason it makes it slightly risky for the user to be able to customize this var since it is somewhat coupled to our plugin implementation.

It might be worth considering whether we have to be more strict on this requirement (say by preventing copilot mode from activating unless some override var is set) or by automatically installing/upgrading the server?
@zerolfx @jcs090218

2024-02-04 14:00 UTC, emil-vdw commented on copilot.el
> +                                                         (generate-new-buffer-name (format "*copilot-install: %s*" name))))
We are not going to install a variety of different servers and the buffer name is confusing since we don't install npm.
```suggestion
                                                         (generate-new-buffer-name "*copilot-install-server*")))
```

2024-02-04 14:00 UTC, emil-vdw commented on copilot.el
> +                                                                        (concat copilot--dist-dir "/agent.js"))
On Linux, this doesn't work for me. There is an executable that is distributed by the npm package and changing it to this works for me:
```suggestion
                                                                        (f-join copilot-install-dir "bin" "copilot-node-server"))
```

2024-02-07 09:13 UTC, jcs090218 commented on copilot.el
> +                                                                        (concat copilot--dist-dir "/agent.js"))
I've changed the variable `copilot--dist-dir`. Does that work for your? 🤔 

```elisp
(defconst copilot--dist-dir
  (if (eq system-type 'windows-nt)
      (f-join copilot-install-dir "node_modules" "copilot-node-server" "copilot" "dist")
    (f-join copilot-install-dir "bin" "copilot-node-server"))
  "The dist directory containing agent.js file.")
```

2024-02-07 09:25 UTC, jcs090218 commented on copilot.el
> +      (message "[WARN] Newer versions of the Copilot server are available for installation.
I have a few thoughts on this:

1. Ignore it, but always support the latest version until the copilot is stable (less compatibility breakage).
2. Add another variable `copilot-preferred-version` and warn the user.
3. Document it somewhere on the README.md

I don't mind any approaches since there is no ideal solution, just personal preferences. 🤔

2024-02-07 09:29 UTC, jcs090218 commented
> 1. The reliability of the copilot-node-server npm package. Can we trust it to be available, up-to-date and not to be hijacked? Should we investigate whether to pull the agent distributables straight from the corresponding github tag of the official copilot.vim repo?

I don't know much about the upstream `copilot.vim`, so I cannot suggest this. However, downloading npm packages seems very common in the Emacs world; use `lsp-mode` and `lsp-grammarly` as examples.

2024-02-07 09:40 UTC, emil-vdw commented
I'm not sure but those examples may be using official distributions (albeit through npm). The copilot vim is an official github owned (official copilot) repository so it can be relied upon. The npm package being installed by us through npm is not official and we should at least strongly consider pulling from the official distribution instead.

In my opinion there should be very good reasons for using the unofficial distribution instead.

2024-02-07 09:48 UTC, jcs090218 commented
Ah, okay. I thought `copilot-node-server` is the official... How about publishing our own npm package? Like [lsp-grammarly](https://github.com/emacs-grammarly/lsp-grammarly) maintains its own [grammarly-language-server](https://github.com/emacs-grammarly/grammarly-language-server). 🤔

2024-02-07 09:50 UTC, zerolfx commented
I found the npm package `copilot-node-server` from https://github.com/TerminalFi/LSP-copilot a long while ago, which is another unofficial Copilot plugin for Sublime. The NPM package is maintained at https://github.com/jfcherng/copilot-node-server.

Maybe we can use it for now and later switch to our own NPM package.

2024-02-07 09:52 UTC, jcs090218 commented
> Maybe we can use it for now and later switch to our own NPM package.

Yeah, I second this. It would take me some time to do this. Plus, it would make this PR too big if it was implemented in the same PR.

2024-02-07 11:05 UTC, emil-vdw commented on copilot.el
> +      (message "[WARN] Newer versions of the Copilot server are available for installation.
It may be fine now the way it is if we document it well in the readme and the `defcustom` as well. That the default version should be modified at the users own risk and that the default on that defcustom is what is currently supported by `copilot.el`.

How does that sound?

2024-02-08 10:21 UTC, jcs090218 commented on copilot.el
> +      (message "[WARN] Newer versions of the Copilot server are available for installation.
I've documented in the `defcustom`, but I don't know where to document on the README. 🤔

2024-02-11 11:57 UTC, emil-vdw commented on copilot.el
> +      (message "[WARN] Newer versions of the Copilot server are available for installation.
Actually, the `defcustom` comment is enough.

2024-02-11 12:59 UTC, emil-vdw commented
@jcs090218 I have added some commits to fix some bugs and support Linux. I don't have access to push to your branch though.

2024-02-11 13:12 UTC, jcs090218 commented
Merged! :)

2024-02-11 13:16 UTC, emil-vdw commented
Would you mind testing those changes on Windows again as well?

2024-02-12 00:27 UTC, jcs090218 commented
> Would you mind testing those changes on Windows again as well?

Yeah, it works now! :)

2024-02-12 00:28 UTC, jcs090218 commented on copilot.el
> +              "bin" "copilot-node-server")
I've simplified it using the same `bin/copilot-node-server` script.

2024-02-12 00:28 UTC, jcs090218 commented on copilot.el
>    (copilot--dbind
The rest are indentation errors.

2024-02-17 09:38 UTC, emil-vdw approved these changes
Remember to pull main (jsonrpc error handling changes).

Thank you for all of your work on this project! You should have write access now and I will make sure you can merge without review (although try to get a review when practicable).

2024-02-17 09:38 UTC, emil-vdw commented on copilot.el
> +   ((not (file-exists-p copilot-install-dir))
This did not catch the condition correctly when I uninstalled the copilot server (this directory is still present). Maybe make it more reliable?

2024-02-17 09:38 UTC, emil-vdw commented on readme.md
> +Current maintainer: [@emil-vdw][], [@rakotomandimby][].
```suggestion
Current maintainer: [@emil-vdw][], [@jcs090218][], [@rakotomandimby][].
```

2024-02-17 09:38 UTC, emil-vdw commented on readme.md
> +[@rakotomandimby]: https://github.com/rakotomandimby
```suggestion
[@jcs090218]: https://github.com/jcs090218
[@rakotomandimby]: https://github.com/rakotomandimby
```

2024-02-17 10:12 UTC, jcs090218 commented on copilot.el
> +   ((not (file-exists-p copilot-install-dir))
How did you uninstall the server? 🤔 The `copilot-install-dir` will be gone if you uninstall it through `M-x copilot-uninstall-server`.

2024-02-17 11:42 UTC, emil-vdw commented on copilot.el
> +   ((not (file-exists-p copilot-install-dir))
Ah that makes sense. I did:
```
npm -g --prefix ~/.emacs.d/.cache/copilot uninstall copilot-node-server
```

2024-02-17 11:47 UTC, emil-vdw commented
Shall we do the cleanup in a subsequent PR @jcs090218 @zerolfx?

2024-02-17 13:08 UTC, emil-vdw commented
I think it's fine to clean up in a subsequent PR. Feel free to merge :+1:.

2024-02-17 17:44 UTC, merged

2024-02-18 22:53 UTC, sho-87 commented
this seems to install (or try to start) copilot server at the wrong location: 

```
[stderr] node:internal/modules/cjs/loader:1152
[stderr]   throw err;
[stderr]   ^
[stderr] 
[stderr] Error: Cannot find module 'c:\Users\simon\.emacs.d\.cache\copilot\node_modules\copilot-node-server\copilot\bin\copilot-node-server'
[stderr]     at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
[stderr]     at Module._load (node:internal/modules/cjs/loader:990:27)
[stderr]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
[stderr]     at node:internal/main/run_main_module:28:49 {
[stderr]   code: 'MODULE_NOT_FOUND',
[stderr]   requireStack: []
[stderr] }
[stderr] 
[stderr] Node.js v21.6.1
```

the extra `bin` before `copilot` leads to the wrong directory

2024-02-18 23:03 UTC, jcs090218 commented
You are right. It's weird since I did applied the change but it some how got reverted. 🤔 

I'm on it.

2024-02-18 23:09 UTC, jcs090218 commented
FYI, I've opened the fix in #267. However, I cannot merge PRs without other maintainer's approval. Therefore, the current workaround is to update `copilot--server-executable` manually. 

```elisp
(setq copilot--server-executable (f-join copilot-install-dir "node_modules" "copilot-node-server" "bin" "copilot-node-server"))
```

2024-02-19 07:01 UTC, jmcarcell commented
When opening emacs with this PR I get the following it complains that I should use `copilot-install-server` but when I try I get
`Symbol's value as variable is void: package`

2024-02-19 07:17 UTC, jcs090218 commented
Can you try `toggle-debug-on-error`? And paste the backtrack here. Thanks!

2024-02-19 07:24 UTC, jmcarcell commented
```Debugger entered--Lisp error: (void-variable package)
  copilot-install-server()
  funcall-interactively(copilot-install-server)
  call-interactively(copilot-install-server record nil)
  command-execute(copilot-install-server record)
  execute-extended-command(nil "copilot-install-server" "install copilot")
  funcall-interactively(execute-extended-command nil "copilot-install-server" "install copilot")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
Indeed, I get this with main but don't get it if I checkout right before this PR

2024-02-19 07:58 UTC, jcs090218 commented
I've made a fix in #268. Thanks for the bug report!